Repository CA-G12/Blog_Pro, pull requests merged in 2022-08, with the labels that each got.

#2 create public folder for client and server folder contains database, …
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/JS/dom.js
  public/JS/logic.js
  public/index.html
  public/posts.html
  public/style.css
  server/app.js
  server/controllers/index.js
  server/database/config/index.js
  server/database/queries/.gitkeep
  server/index.js
  server/router/index.js
  tests/database.js
  tests/logic.js
  tests/routes.js
Labels: merged

#11 create tables and add fact data relates #3
  server/database/config/init.sql
Labels: merged

#16 4 create server
  package.json
  server/app.js
  server/index.js
Labels: merged

#18 13 create posts page
  public/posts.html
  public/style.css
Labels: merged

#19 add new post to databace #8
  package.json
  public/JS/dom.js
  public/index.html
  public/posts.html
  server/app.js
  server/controllers/index.js
  server/controllers/postData.js
  server/database/queries/index.js
  server/database/queries/postData.js
  server/index.js
  server/router/index.js
Labels: merged

#20 7 create getposts query
  public/JS/dom.js
  public/posts.html
  server/app.js
  server/controllers/getData.js
  server/database/queries/.gitkeep
  server/database/queries/getData.js
  server/router/index.js
Labels: approved

#21 create build function relates #6
  server/database/config/build.js
Labels: approved

#23 create github action #8
  .gethub/workflows/Test.yml
  package-lock.json
  package.json
  server/controllers/postData.js
  tests/routes.js
  tests/routes.test.js
Labels: merged

#24 fix the test
  .eslintrc.json
  .github/workflows/Test.yml
  package-lock.json
  package.json
  tests/routes.test.js
Labels: awaiting-review

#27 create profile
  .github/workflows/Test.yml
  Procfile
  server/app.js
  server/database/config/connection.js
Labels: merged

#26 create test for get posts
  .github/workflows/Test.yml
  tests/routes.test.js
Labels: merged

#28 edit the dom for create posts
  public/JS/dom.js
Labels: merged

#29 Addpost tosection
  public/JS/dom.js
  public/posts.html
  server/controllers/getComment.js
  server/controllers/index.js
  server/controllers/postData.js
  server/database/queries/getComment.js
  server/database/queries/index.js
  server/router/index.js
  tests/routes.test.js
Labels: merged

#30 show the posts comment
  public/JS/dom.js
  server/controllers/getComment.js
  server/database/queries/getComment.js
  server/router/index.js
Labels: awaiting-review

#31 create post comments query relates #9
  Procfile
  public/JS/dom.js
  server/controllers/index.js
  server/controllers/postComment.js
  server/database/queries/index.js
  server/database/queries/postComment.js
  server/router/index.js
Labels: approved

#33 create landing page and style it relates #12
  public/index.html
  public/style.css
Labels: approved

#35 delete the post
  public/JS/dom.js
  public/style.css
  server/controllers/deletePost.js
  server/controllers/getComment.js
  server/controllers/index.js
  server/database/queries/deletePost.js
  server/database/queries/index.js
  server/router/index.js
Labels: merged

#38 write read me file contains description and layout relates #34
  README.md
Labels: approved

#37 edit the html and css to make responsive design
  public/index.html
  public/style.css
Labels: approved

#36 add new posts in sql file
  server/database/config/init.sql
Labels: approved
